
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import org.markdown4j.Markdown4jProcessor;


/**
 *
 * @author s137p379
 */
public class Markdown3Pane extends javax.swing.JFrame {

	/**
	 * Creates new form markdown3Pane
	 */
	public Markdown3Pane() {
		setTitle("Markdown Preview");
		style();
		initComponents();
		setupSample();
		render();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneInput = new javax.swing.JTextPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPaneView = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPaneSource = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(120);
        jSplitPane1.setResizeWeight(0.5);

        jTextPaneInput.setToolTipText("Input");
        jTextPaneInput.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jTextPaneInputCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jTextPaneInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextPaneInputKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextPaneInput);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jSplitPane2.setDividerLocation(200);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setResizeWeight(0.5);

        jScrollPane3.setViewportView(jEditorPane2);

        jSplitPane2.setTopComponent(jScrollPane3);

        jEditorPaneView.setEditable(false);
        jEditorPaneView.setContentType("text/html"); // NOI18N
        jEditorPaneView.setToolTipText("Html View");
        jScrollPane4.setViewportView(jEditorPaneView);

        jSplitPane2.setTopComponent(jScrollPane4);

        jTextPaneSource.setEditable(false);
        jTextPaneSource.setToolTipText("Html Text");
        jScrollPane5.setViewportView(jTextPaneSource);

        jSplitPane2.setRightComponent(jScrollPane5);

        jSplitPane1.setRightComponent(jSplitPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPaneInputCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextPaneInputCaretPositionChanged
		// TODO add your handling code here:
		

    }//GEN-LAST:event_jTextPaneInputCaretPositionChanged

    private void jTextPaneInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPaneInputKeyReleased
        // TODO add your handling code here:
		int code = evt.getKeyCode();
		if(code==10){
			System.out.println("<ENTER>");
			render();
		}

    }//GEN-LAST:event_jTextPaneInputKeyReleased

	private void render() {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					String markdown = jTextPaneInput.getText();
					System.out.println("markdown = " + markdown);

					String html = new Markdown4jProcessor().process(markdown);
					System.out.println("html = " + html);
					jEditorPaneView.setText(html);
					jTextPaneSource.setText(html);

				} catch (IOException ex) {
					Logger.getLogger(Markdown3Pane.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
		});
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Markdown3Pane().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JEditorPane jEditorPaneView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextPane jTextPaneInput;
    private javax.swing.JTextPane jTextPaneSource;
    // End of variables declaration//GEN-END:variables

	private void style() {
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (Exception ex) {
			Logger.getLogger(Markdown3Pane.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void setupSample() {
		String sample = "A First Level Header \n"
				+ "====================  \n"
				+ "A Second Level Header \n"
				+ "---------------------  \n"
				+ "Now is the time for all good men to come to the aid of their country. This is just a regular paragraph.  \n"
				+ "The quick brown fox jumped over the lazy dog's back.  \n"
				+ "### Header 3  \n"
				+ "> This is a blockquote. \n"
				+ ">  \n"
				+ "> This is the second paragraph in the blockquote. \n"
				+ "> \n"
				+ "> ## This is an H2 in a blockquote\n"
				+ "\n"
				+ "\n"
				+ "Some of these words *are emphasized*.\n"
				+ "Some of these words _are emphasized also_.\n"
				+ "\n"
				+ "Use two asterisks for **strong emphasis**.\n" 
				+ "Or, if you prefer, __use two underscores instead__.\n"
				+ "\n"
				+ "- Candy.\n"
				+ "- Gum.\n"
				+ "- Booze.\n"
				+ "\n"
				+ "####more list\n"
				+ "1. Red\n"
				+ "2. Green\n"
				+ "3. Blue\n"
				+ "\n"
				+ "#### links\n"
				+ "This is an [example link](http://example.com/).\n"
				+ "\n"
				+ "#### more link\n"
				+ "I get 10 times more traffic from [Google][1] than from\n"
				+ "[Yahoo][2] or [MSN][3].\n"
				+ "\n"
				+ "[1]: http://google.com/        \"Google\"\n"
				+ "[2]: http://search.yahoo.com/  \"Yahoo Search\"\n"
				+ "[3]: http://search.msn.com/    \"MSN Search\""
				+ "\n"
				+ "#### code\n"
				+ "I strongly recommend against using any `<blink>` tags.\n"
				+ "\n"
				+ "I wish SmartyPants used named entities like `&mdash;`\n"
				+ "instead of decimal-encoded entites like `&#8212;`.\n"
				+ "\n"
				+ "#### tables\n"
				+ "Markdown | Less | Pretty\n"
				+"--- | --- | ---\n"
				+"*Still* | `renders` | **nicely**\n" 
				+"1 | 2 | 3\n"
				+ "\n"
				+ "\n"
				+ "\n";
		jTextPaneInput.setText(sample);
	}
}
