
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author B
 */
public class StringSubmarine extends javax.swing.JFrame {

    /**
     * Creates new form StringSubmarine
     */
    public StringSubmarine() {
        style();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaOutput = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaInput = new javax.swing.JTextArea();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListFunctionName = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaFunctionDefinition = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.5);

        jTextAreaOutput.setEditable(false);
        jTextAreaOutput.setColumns(20);
        jTextAreaOutput.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jTextAreaOutput.setRows(5);
        jTextAreaOutput.setToolTipText("Input");
        jScrollPane4.setViewportView(jTextAreaOutput);

        jSplitPane1.setLeftComponent(jScrollPane4);

        jTextAreaInput.setColumns(20);
        jTextAreaInput.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jTextAreaInput.setRows(5);
        jTextAreaInput.setToolTipText("Ouput");
        jScrollPane3.setViewportView(jTextAreaInput);

        jSplitPane1.setRightComponent(jScrollPane3);

        jSplitPane2.setDividerLocation(100);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setResizeWeight(0.5);

        jListFunctionName.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListFunctionName.setToolTipText("Function Names");
        jListFunctionName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jListFunctionNameMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jListFunctionName);

        jSplitPane2.setLeftComponent(jScrollPane1);

        jTextAreaFunctionDefinition.setColumns(20);
        jTextAreaFunctionDefinition.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jTextAreaFunctionDefinition.setRows(5);
        jTextAreaFunctionDefinition.setTabSize(4);
        jTextAreaFunctionDefinition.setToolTipText("Function Definition");
        jScrollPane2.setViewportView(jTextAreaFunctionDefinition);

        jSplitPane2.setRightComponent(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 169, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jSplitPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSplitPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListFunctionNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListFunctionNameMouseReleased
        // TODO add your handling code here:
        System.out.println("jListFunctionNameMouseReleased");
        if(evt.getClickCount()==2){
            System.out.println("DOUBLE CLICK");
            
            String newName = JOptionPane.showInputDialog(this,
                    "message", "title", 
                    JOptionPane.QUESTION_MESSAGE);
            
            if(newName!=null && !newName.isEmpty()){
                System.out.println("newName = " + newName);
                
                
                
            }
            
        }else{
            System.out.println("SINGLE CLICK");
        }
    }//GEN-LAST:event_jListFunctionNameMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StringSubmarine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JList<String> jListFunctionName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextArea jTextAreaFunctionDefinition;
    private javax.swing.JTextArea jTextAreaInput;
    private javax.swing.JTextArea jTextAreaOutput;
    // End of variables declaration//GEN-END:variables

    private void style() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            Logger.getLogger(StringSubmarine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
